---
functional:
  - Пользователь может зарегистрироваться используя емаил почту, аккуанут гитхаб или дискорд.
  - Пользователь может авторизоваться используя емаил почту, аккуанут гитхаб или дискорд.
  - Пользователь может менять язык программирования во время игры.
  - Игрок во время игры может видеть редактор с кодом противника.
  - В игру можно сыграть с ботом.
  - В игру можно сыграть с другом, которому отправлена ссылка на игру.
  - При создании игры пользователь может самостоятельно выбрать игру.
  - При создании игры пользователь может самостоятельно выбрать сложность игры.
  - Задачи доступны в двух языках, русском и английском.
  - На сайте доступен  список завершенных игр.
  - Пользователь может посмотреть любую состоявшуюся игру в записи.
  - Пользователь может смотреть онлайн-трансляцию чужой игры.
  - Игроки получают очки за победу в игре.
  - На сайте есть 3 рейтинга игроков,за неделю, за месяц , и за всё время. Он строится на основе заработанных очков.
  
non-functional:
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть совместим с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Cайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  
implicit:
  - Игрок не имеет возможности писать что-либо в редактор кода противника.
  - Невозможно вручную вписать количество баллов какому-либо игроку.
